# Generated by Django 2.1.3 on 2019-01-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='myblog',
        ),
    ]
